version: '3'
services:
  mockpad-redis:
    image: redis:5.0-rc4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks: 
      - backend
    entrypoint: redis-server --appendonly yes
    extra_hosts:
      - "dockerhost:$DOCKERHOST"
  mockpad-server:
    build: 
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "3000:3000"
    networks: 
      - backend
    volumes:
      - ./client:/code/client
      - ./server:/code/server
    depends_on:
      - mockpad-redis
    command: node /code/server/server.js
    extra_hosts:
      - "dockerhost:$DOCKERHOST"
  mockpad-executor:
    build:
      context: .
      dockerfile: executor.Dockerfile
    image: mockpad-executor
    extra_hosts:
      - "dockerhost:$DOCKERHOST"
networks: 
  backend:
    driver: bridge