version: '3'
services:
  redis:
    image: redis:5.0-rc4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks: 
      - backend
    entrypoint: redis-server --appendonly yes
  server:
    build: ./
    ports:
      - "3000:3000"
    networks: 
      - backend
    volumes:
      - ./client:/code/client
      - ./server:/code/server
    depends_on:
      - redis
    command: node /code/server/server.js
networks: 
  backend:
    driver: bridge